In [12]:
import pandas as pd
import numpy as np
import time

In [13]:
wins

NameError: name 'wins' is not defined

In [14]:
df

   Team   W   L   W/L%    GB   PS/G   PA/G   SRS
0   MIL  58  24  0.707     —  116.9  113.3  3.61
1   BOS  57  25  0.695   1.0  117.9  111.4  6.38
2   PHI  54  28  0.659   4.0  115.2  110.9  4.37
3   CLE  51  31  0.622   7.0  112.3  106.9  5.23
4   NYK  47  35  0.573  11.0  116.0  113.1  2.99
5   BKN  45  37  0.549  13.0  113.4  112.5  1.03
6   MIA  44  38  0.537  14.0  109.5  109.8 -0.13
7   ATL  41  41  0.500  17.0  118.4  118.1  0.32
8   TOR  41  41  0.500  17.0  112.9  111.4  1.59
9   CHI  40  42  0.488  18.0  113.1  111.8  1.37
10  IND  35  47  0.427  23.0  116.3  119.5 -2.91
11  WAS  35  47  0.427  23.0  113.2  114.4 -1.06
12  ORL  34  48  0.415  24.0  111.4  114.0 -2.39
13  CHA  27  55  0.329  31.0  111.0  117.2 -5.89
14  DET  17  65  0.207  41.0  110.3  118.5 -7.73
0   DEN  53  29  0.646     —  115.8  112.5  3.04
1   MEM  51  31  0.622   2.0  116.9  113.0  3.60
2   SAC  48  34  0.585   5.0  120.7  118.1  2.30
3   PHX  45  37  0.549   8.0  113.6  111.6  2.08
4   LAC  44  38  0.537   9.0  113.6  113.1  0.31
5   GSW  44  38  0.537   9.0  118.9  117.1  1.66
6   LAL  43  39  0.524  10.0  117.2  116.6  0.43
7   MIN  42  40  0.512  11.0  115.8  115.8 -0.22
8   NOP  42  40  0.512  11.0  114.4  112.5  1.63
9   OKC  40  42  0.488  13.0  117.5  116.4  0.96
10  DAL  38  44  0.463  15.0  114.2  114.1 -0.14
11  UTA  37  45  0.451  16.0  117.1  118.0 -1.03
12  POR  33  49  0.402  20.0  113.4  117.4 -3.96
13  HOU  22  60  0.268  31.0  110.7  118.6 -7.62
14  SAS  22  60  0.268  31.0  113.0  123.1 -9.82